# Git Lab agent

# token = xxxxxxxx
# echo -n 'xxxxxxxxxxxx' | base64  is xxxxxxxxxxzV3lnaG9ORjFwUVBMNFZEZkoyTV92UnpyWVVaZTdIeUNQbkE=
# Below tokens are NOT VALID
---
apiVersion: v1
kind: Namespace
metadata:
  name: gitlab-k8s-agent

---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-k8s-agent-token
  namespace: gitlab-k8s-agent
type: Opaque
data:
  token: d2l6cEhjUHN4aVV3TFJzV3lnaG9ORjFwUVBMNFZEZkoyTV92UnpyWVVaZTdIeUNQbkE=
  
---  
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: sa-gitlab-k8s-agent
    namespace: gitlab-k8s-agent
  ---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: deploy-gitlab-k8s-agent
    namespace: gitlab-k8s-agent
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: gitlab-k8s-agent
    template:
      metadata:
        labels:
          app: gitlab-k8s-agent
        namespace: gitlab-k8s-agent
      spec:
        serviceAccountName: sa-gitlab-k8s-agent
        containers:
        - name: agent
          image: "registry.gitlab.com/gitlab-org/cluster-integration/gitlab-agent/agentk:stable"
          args:
          - --token-file=/config/token
          - --kas-address
          - wss://kas.gitlab.com # for GitLab.com users, use this KAS.
          volumeMounts:
          - name: token-volume
            mountPath: /config
		      env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name

        volumes:
        - name: token-volume
          secret:
            secretName: 	
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1
  ---
  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: clusterrole-gitlab-k8s-agent-write-cm
  rules:
  - resources:
    - 'configmaps'
    apiGroups:
    - ''
    verbs:
    - create
    - update
    - delete
    - patch
  ---
  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: clusterrolebinding-gitlab-k8s-agent-write-cm
  roleRef:
    name: clusterrole-gitlab-k8s-agent-write-cm
    kind: ClusterRole
    apiGroup: rbac.authorization.k8s.io
  subjects:
  - name: sa-gitlab-k8s-agent
    kind: ServiceAccount
    namespace: gitlab-k8s-agent
  ---
  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: clusterrole-gitlab-k8s-agent-read-cm
  rules:
  - resources:
    - 'configmaps'
    apiGroups:
    - ''
    verbs:
    - get
    - list
    - watch
  ---
  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: clusterrolebinding-gitlab-k8s-agent-read-cm
  roleRef:
    name: clusterrole-gitlab-k8s-agent-read-cm
    kind: ClusterRole
    apiGroup: rbac.authorization.k8s.io
  subjects:
  - name: sa-gitlab-k8s-agent
    kind: ServiceAccount
    namespace: gitlab-k8s-agent
  ---
  apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    namespace: gitlab-k8s-agent
    name: role-gitlab-k8s-agent-write
  rules:
  - resources:
    - '*'
    apiGroups:
    - '*'
    verbs:
    - create
    - update
    - delete
    - patch
  ---
  apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    namespace: gitlab-k8s-agent
    name: rolebinding-gitlab-k8s-agent-write
  roleRef:
    name: role-gitlab-k8s-agent-write
    kind: Role
    apiGroup: rbac.authorization.k8s.io
  subjects:
  - name: sa-gitlab-k8s-agent
    kind: ServiceAccount
    namespace: gitlab-k8s-agent
  ---
  apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    namespace: gitlab-k8s-agent
    name: role-gitlab-k8s-agent-read
  rules:
  - resources:
    - '*'
    apiGroups:
    - '*'
    verbs:
    - get
    - list
    - watch
  ---
  apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    namespace: gitlab-k8s-agent
    name: rolebinding-gitlab-k8s-agent-read
  roleRef:
    name: role-gitlab-k8s-agent-read
    kind: Role
    apiGroup: rbac.authorization.k8s.io
  subjects:
  - name: sa-gitlab-k8s-agent
    kind: ServiceAccount
    namespace: gitlab-k8s-agent
  ---
  apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    namespace: dude
    name: role-gitlab-k8s-agent-write-dude
  rules:
  - resources:
    - '*'
    apiGroups:
    - '*'
    verbs:
    - create
    - update
    - delete
    - patch
  ---
  apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    namespace: dude
    name: rolebinding-gitlab-k8s-agent-write-binding-dude
  roleRef:
    name: role-gitlab-k8s-agent-write-dude
    kind: Role
    apiGroup: rbac.authorization.k8s.io
  subjects:
  - name: sa-gitlab-k8s-agent
    kind: ServiceAccount
    namespace: gitlab-k8s-agent
  ---
  apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    namespace: dude
    name: role-gitlab-k8s-agent-read-dude
  rules:
  - resources:
    - '*'
    apiGroups:
    - '*'
    verbs:
    - get
    - list
    - watch
  ---
  apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    namespace: dude
    name: rolebinding-gitlab-k8s-agent-read-binding-dude
  roleRef:
    name: role-gitlab-k8s-agent-read-dude
    kind: Role
    apiGroup: rbac.authorization.k8s.io
  subjects:
  - name: sa-gitlab-k8s-agent
    kind: ServiceAccount
    namespace: gitlab-k8s-agent